## plot1.R
library(lubridate)
library(dplyr)
d<-read.csv("household_power_consumption.txt",sep=";",na.strings="?")
d$Date<-dmy(d$Date)
d1 <- filter(d, Date == ymd("20070201") | Date == ymd("20070202"))
d1$Time <- hms(d1$Time)
png(filename = "plot1.png")
hist(as.numeric(d1$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()